language: python
python:
- '3.6'
install:
- pip install aos-signer
before_install:
- openssl aes-256-cbc -K $encrypted_511c10f01f4a_key -iv $encrypted_511c10f01f4a_iv
  -in meta/private_key.pem.enc -out meta/private_key.pem -d
script:
- aos-signer sign
- aos-signer upload
